services:

  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination ./mlruns
    volumes:
     - ./modelos:/mlruns
    container_name: tracking
    ports:
     - "5000:5000"


 # diabeter-predition-service:
  diabetes-predition-service:
    build:
      context: .
      dockerfile: Dockerfile.Service 
      tags:
        - diabetes-predition-service
        - ghcr.io/filipalagoa/diabetes-predition-service 
    image: diabetes-predition-service
    container_name: service
    ports:
     - 5002:5002



  diabetes-predition-ui:
    build:
      context: .
      dockerfile: Dockerfile.UI
      tags:
        - diabetes-predition-ui
    image: diabetes-predition-ui
    container_name: ui
    ports:
      - 5003:5003

