name: Simple CI/CD

on:
  push:  

jobs:
  simpleci:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3 
      - name: Listar diretório
        run: ls -lah